from models import Twitter, RedditPostTable, RedditCommentTable, Github
import datetime


async def populate_twitter():
    await Twitter.bulk_create(
        [
            Twitter(
                tweet_id=1611245321,
                tweet="Hey! First tweet. Great!",
                posted_at=datetime.datetime(2022, 1, 15, 14, 51, 42),
                day_of_week=5,
                day=15,
                month=1,
                year=2022,
                hour=14,
                mins=51,
                likes=34,
                retweets=12,
                sentiment_score=0.7,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=1611245322,
                tweet="Hey! Second tweet. Lovely!",
                posted_at=datetime.datetime(2022, 2, 21, 10, 30, 2),
                day_of_week=0,
                day=21,
                month=2,
                year=2022,
                hour=10,
                mins=30,
                likes=19,
                retweets=2,
                sentiment_score=0.65,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=1611245323,
                tweet="Oops! another tweet again. Sad!",
                posted_at=datetime.datetime(2022, 2, 28, 8, 30, 2),
                day_of_week=0,
                day=28,
                month=2,
                year=2022,
                hour=8,
                mins=30,
                likes=3,
                retweets=1,
                sentiment_score=0.35,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=1611245324,
                tweet="Sad! Very horribly bad",
                posted_at=datetime.datetime(2022, 4, 22, 17, 20, 45),
                day_of_week=4,
                day=22,
                month=4,
                year=2022,
                hour=17,
                mins=20,
                likes=13,
                retweets=5,
                sentiment_score=0.1,
                asa_id="ChoiceCoin",
            ),
        ]
    )


async def populate_post():
    await RedditPostTable.bulk_create(
        [
            RedditPostTable(
                post_id="3752125",
                title="post 1",
                text="text for post 1",
                score=35,
                num_of_comments=3,
                time_created=datetime.datetime(2022, 1, 15, 14, 51, 42),
                day_of_week=5,
                day=15,
                month=1,
                year=2022,
                hour=14,
                mins=51,
                url="url.com",
                sentiment_score=0.7,
                asa_id="ChoiceCoin",
            ),
            RedditPostTable(
                post_id="2569278",
                title="post 2",
                text="text for post 2",
                score=13,
                num_of_comments=2,
                time_created=datetime.datetime(2022, 2, 28, 8, 30, 2),
                day_of_week=0,
                day=28,
                month=2,
                year=2022,
                hour=8,
                mins=30,
                url="url.com",
                sentiment_score=0.3,
                asa_id="ChoiceCoin",
            ),
            RedditPostTable.create(
                post_id="2737402",
                title="post 2",
                text="text for post 2",
                score=13,
                num_of_comments=1,
                time_created=datetime.datetime(2022, 4, 22, 17, 20, 45),
                day_of_week=4,
                day=22,
                month=4,
                year=2022,
                hour=17,
                mins=20,
                url="url.com",
                sentiment_score=0.5,
                asa_id="ChoiceCoin",
            ),
        ]
    )


async def populate_comments():
    await RedditCommentTable.bulk_create(
        [
            RedditCommentTable(
                comment_id="1005114",
                body="comment 1",
                score=21,
                time_created=datetime.datetime(2022, 1, 15, 15, 51, 42),
                day_of_week=5,
                day=15,
                month=1,
                year=2022,
                hour=15,
                mins=51,
                sentiment_score=0.7,
                post_id="3752125",
            ),
            RedditCommentTable(
                comment_id="1805475",
                body="comment 2",
                score=11,
                time_created=datetime.datetime(2022, 1, 15, 17, 51, 42),
                day_of_week=5,
                day=17,
                month=1,
                year=2022,
                hour=15,
                mins=51,
                sentiment_score=0.65,
                post_id="3752125",
            ),
            RedditCommentTable(
                comment_id="120024",
                body="comment 3",
                score=21,
                time_created=datetime.datetime(2022, 1, 15, 21, 51, 42),
                day_of_week=5,
                day=15,
                month=1,
                year=2022,
                hour=21,
                mins=51,
                sentiment_score=0.65,
                post_id="3752125",
            ),
            ######################
            RedditCommentTable(
                comment_id="8753656",
                body="comment 1",
                score=11,
                time_created=datetime.datetime(2022, 2, 28, 8, 55, 2),
                day_of_week=0,
                day=28,
                month=2,
                year=2022,
                hour=8,
                mins=55,
                sentiment_score=0.7,
                post_id="2569278",
            ),
            RedditCommentTable(
                comment_id="7189372",
                body="comment 1",
                score=1,
                time_created=datetime.datetime(2022, 2, 28, 19, 35, 2),
                day_of_week=0,
                day=28,
                month=2,
                year=2022,
                hour=19,
                mins=35,
                sentiment_score=0.7,
                post_id="2569278",
            ),
            #########################
            RedditCommentTable(
                comment_id="7718031",
                body="comment 1",
                score=21,
                time_created=datetime.datetime(2022, 4, 24, 17, 20, 45),
                day_of_week=6,
                day=24,
                month=4,
                year=2022,
                hour=17,
                mins=20,
                sentiment_score=0.7,
                post_id="2737402",
            ),
            #######################
        ]
    )


async def populate_github():
    await Github.bulk_create(
        [
            Github(
                repo_name="repo1",
                repo_desc="desc 1",
                date_created=datetime.datetime(2022, 4, 24, 17, 20, 45),
                dc_day_of_week=2,
                dc_day=24,
                dc_month=4,
                dc_year=2022,
                dc_hr=17,
                dc_mins=20,
                last_push_date=datetime.datetime(2022, 6, 24, 17, 20, 45),
                lp_day_of_week=4,
                lp_day=24,
                lp_month=6,
                lp_year=2022,
                lp_hr=17,
                lp_mins=20,
                language="python",
                no_of_forks=12,
                no_of_stars=34,
                no_of_watches=45,
                no_of_contributors=34,
                no_of_commits=234,
                issues=123,
                pull_requests=12,
                asa_id="ChoiceCoin",
            ),
            Github(
                repo_name="repo2",
                repo_desc="desc 2",
                date_created=datetime.datetime(2022, 4, 25, 17, 20, 45),
                dc_day_of_week=3,
                dc_day=25,
                dc_month=4,
                dc_year=2022,
                dc_hr=17,
                dc_mins=20,
                last_push_date=datetime.datetime(2022, 6, 28, 17, 20, 45),
                lp_day_of_week=1,
                lp_day=28,
                lp_month=6,
                lp_year=2022,
                lp_hr=17,
                lp_mins=20,
                language="python",
                no_of_forks=12,
                no_of_stars=34,
                no_of_watches=45,
                no_of_contributors=34,
                no_of_commits=234,
                issues=123,
                pull_requests=12,
                asa_id="ChoiceCoin",
            ),
            Github(
                repo_name="repo3",
                repo_desc="desc 3",
                date_created=datetime.datetime(2022, 5, 24, 17, 20, 45),
                dc_day_of_week=1,
                dc_day=24,
                dc_month=5,
                dc_year=2022,
                dc_hr=17,
                dc_mins=20,
                last_push_date=datetime.datetime(2022, 7, 1, 17, 20, 45),
                lp_day_of_week=4,
                lp_day=1,
                lp_month=7,
                lp_year=2022,
                lp_hr=17,
                lp_mins=20,
                language="python",
                no_of_forks=12,
                no_of_stars=34,
                no_of_watches=45,
                no_of_contributors=34,
                no_of_commits=234,
                issues=123,
                pull_requests=12,
                asa_id="ChoiceCoin",
            ),
        ]
    )
